### ISSUE TITLE
No tags/releases in upstream repository

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-bfl#1]
[rosindex lists ros-gbp](http://rosindex.github.io/p/bfl/) as the checkout URI for this package. I filed another issue like this (can't recall the package) where I was able to use the upstream repo instead, even though rosindex also lists ros-gbp.

For this case, however, there are no tags/releases at all, only at ros-gbp. Their api for tags just returns [an empty list](https://api.github.com/repos/toeklk/orocos-bayesian-filtering/tags).

So, just a notice that I don't think there's anything we can do about this one with respect to moving to upstream unless we go with a `-git` version...

**Comment by acxz** [comment]
I think since the upstream does not have a package.xml it is not meant to be used for ROS, but ROS maintainers have added their own package.xml on top and have released it in ros-gbp as such I think it is appropriate to keep the source for this to be the ros-gbp one.
